# Generated by Django 4.1.5 on 2023-01-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('market', models.CharField(choices=[('FOREX', 'FOREX'), ('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO'), ('FUTURES', 'FUTURES'), ('OPTIONS', 'OPTIONS')], max_length=32)),
                ('assets', models.CharField(max_length=16)),
                ('action', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=32)),
                ('status', models.CharField(choices=[('LOSE', 'LOSE'), ('WIN', 'WIN')], max_length=32)),
                ('types', models.CharField(choices=[('SWING TRADE', 'SWING TRADE'), ('SCALPING', 'SCALPING')], max_length=32)),
                ('risk', models.IntegerField(default=1)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('setup', models.URLField(blank=True, max_length=132)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
