# Generated by Django 4.1.5 on 2023-01-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_trade_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='category',
            field=models.CharField(choices=[('NONE', 'NONE'), ('FOREX', 'FOREX'), ('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO'), ('FUTURES', 'FUTURES'), ('OPTIONS', 'OPTIONS')], default='', max_length=32),
        ),
    ]
