# Generated by Django 4.1.5 on 2023-01-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_trade_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.FloatField(),
        ),
    ]
