# Generated by Django 4.1.5 on 2023-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_trade_balance_alter_trade_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='category',
            field=models.CharField(choices=[('FOREX', 'FOREX'), ('STOCK', 'STOCK'), ('CRYPTO', 'CRYPTO'), ('FUTURES', 'FUTURES'), ('OPTIONS', 'OPTIONS'), ('NONE', 'NONE')], max_length=32),
        ),
    ]
